version: '3.7'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./config/sentinel1.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./config/sentinel2.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf


  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
        - "26381:26379"
    volumes:
        - ./config/sentinel3.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf