spring:
  redis:
    host: 127.0.0.1
    port: 7379
    cluster:
      nodes:
      - "redis://127.0.0.1:7001"
      - "redis://127.0.0.1:7002"
      - "redis://127.0.0.1:7003"
      - "redis://127.0.0.1:7004"
      - "redis://127.0.0.1:7005"
      - "redis://127.0.0.1:7006"
    sentinel:
      master: mymaster
      nodes:
        - "redis://127.0.0.1:26379"
        - "redis://127.0.0.1:26380"
        - "redis://127.0.0.1:26381"
#      nodes:
#        - "redis://127.0.0.1:26379"
#        - "redis://127.0.0.1:26380"
#        - "redis://127.0.0.1:26381"
