version: '3.7'

services:
  master:
    image: redis
    container_name: redis-master
    ports:
      - 7001:6379
    volumes:
      - ./servers/7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 7002:6379
    volumes:
      - ./servers/7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof 10.112.101.43 7001
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 7003:6379
    volumes:
      - ./servers/7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof 10.112.101.43 7001