version: '3.7'

services:
  master:
    image: redis
    container_name: redis-master
    network_mode: "host"
    dns_search: .
    ports:
      - 7001:7001
    volumes:
      - ./redis-sentinel/servers/7001/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  slave1:
    image: redis
    container_name: redis-slave-1
    network_mode: "host"
    dns_search: .
    ports:
      - 7002:7002
    volumes:
      - ./redis-sentinel/servers/7002/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --slaveof 127.0.0.1 7001
    depends_on:
      - master
  slave2:
    image: redis
    container_name: redis-slave-2
    network_mode: "host"
    dns_search: .
    ports:
      - 7003:7003
    volumes:
      - ./redis-sentinel/servers/7003/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --slaveof 127.0.0.1 7001
    depends_on:
      - master

  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    network_mode: "host"
    dns_search: .
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel/config/sentinel26379.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    network_mode: "host"
    dns_search: .
    ports:
      - "26380:26380"
    volumes:
      - ./redis-sentinel/config/sentinel26380.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master


  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    network_mode: "host"
    dns_search: .
    ports:
       - "26381:26381"
    volumes:
        - ./redis-sentinel/config/sentinel26381.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master