version: '3.7'

services:
  master:
    image: redis
    container_name: redis-master
    ports:
      - 7001:7001
    volumes:
      - ./redis-sentinel/servers/7001/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 7002:7002
    volumes:
      - ./redis-sentinel/servers/7002/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --slaveof redis-master 7001
    depends_on:
      - master
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 7003:7003
    volumes:
      - ./redis-sentinel/servers/7003/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --slaveof redis-master 7001
    depends_on:
      - master

  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel/config/sentinel1.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - ./redis-sentinel/config/sentinel2.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master


  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
       - "26381:26379"
    volumes:
        - ./redis-sentinel/config/sentinel3.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - master